### ISSUE TITLE
Use break?

### ISSUE THREAD

**Issue by IanaKhitsko** [AlexandraPV/ttps#3]
https://github.com/AlexandraPV/ttps/blob/f2030cb36aff51e602d0a427bf9c5bf917a04803/lab_2.py#L84

It seems you don't need 'loop' value. Just while (true) and break when you need

**Comment by AlexandraPV** [comment]
In the case of user input, where there is a validating function, using the "while true breake" construct is not entirely correct. Because you need to always monitor the state of the continuation of the cycle.
