### ISSUE TITLE
Get we use bool ?

### ISSUE THREAD

**Issue by IanaKhitsko** [AlexandraPV/ttps#6]
https://github.com/AlexandraPV/ttps/blob/f2030cb36aff51e602d0a427bf9c5bf917a04803/lab_2.py#L170-L174

Can we use just bool variable? Smth like this (I'm not a python dev, sorry):
finished = False
for coun in all_countries:
            finished &= coun.country_finish()
if (finished):
        break

**Comment by AlexandraPV** [comment]
Python hasn't this operation, but has method "all". ( map/reduce approach)
