### ISSUE TITLE
Questions to the format of country 

### ISSUE THREAD

**Issue by isaieva** [AlexandraPV/ttps#8]
https://github.com/AlexandraPV/ttps/blob/b93cdb9ab013161257eccab01d0d199aea414f01/lab_2.py#L86-L98

1. Do you check the length of created countries' names? Task states that it shoud be 25 chars at most

2. Do you check condition for coordinates (1st component of 1st coord <= 1st component of 2nd coord and 2nd component of 1st coord <= 2nd component of 2nd coord) ?

3. Maybe it would be prettier to combine previous condition with your current check for valid coordinates range in separate function?

**Comment by AlexandraPV** [comment]
2. Using the coordinates we are building a rectangle (country) it does not matter whether a larger or smaller coordinate was set first, the rectangle will still be built
